// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlbLmYeHkIPOX2JELO7rqlKXmkZrfAsnM',
    appId: '1:275246812933:web:0490a71d657c7bf66c316c',
    messagingSenderId: '275246812933',
    projectId: 'robin-radio',
    authDomain: 'robin-radio.firebaseapp.com',
    storageBucket: 'robin-radio.appspot.com',
    measurementId: 'G-3FS1J0HFG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxzljYMisByRgddXKfHgIbbVoHtBxBFJg',
    appId: '1:275246812933:android:fee01201b682cf656c316c',
    messagingSenderId: '275246812933',
    projectId: 'robin-radio',
    storageBucket: 'robin-radio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxIDqjlG2N4pjQLFWUF4UgA30oFGksdjs',
    appId: '1:275246812933:ios:fdcccf3a992f9e886c316c',
    messagingSenderId: '275246812933',
    projectId: 'robin-radio',
    storageBucket: 'robin-radio.appspot.com',
    iosBundleId: 'com.robinradio.robinRadio',
  );
}
