// Mocks generated by Mockito 5.4.6 from annotations
// in robin_radio/test/integration/radio_playback_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:just_audio/just_audio.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:robin_radio/models/models.dart' as _i4;
import 'package:robin_radio/services/audio_service.dart' as _i5;
import 'package:robin_radio/services/catalog_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CatalogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatalogService extends _i1.Mock implements _i2.CatalogService {
  MockCatalogService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoaded =>
      (super.noSuchMethod(Invocation.getter(#isLoaded), returnValue: false)
          as bool);

  @override
  _i3.Future<
    ({List<_i4.Album> albums, List<_i4.Artist> artists, List<_i4.Track> tracks})
  >
  loadCatalog() =>
      (super.noSuchMethod(
            Invocation.method(#loadCatalog, []),
            returnValue: _i3.Future<
              ({
                List<_i4.Album> albums,
                List<_i4.Artist> artists,
                List<_i4.Track> tracks,
              })
            >.value((
              albums: <_i4.Album>[],
              artists: <_i4.Artist>[],
              tracks: <_i4.Track>[],
            )),
          )
          as _i3.Future<
            ({
              List<_i4.Album> albums,
              List<_i4.Artist> artists,
              List<_i4.Track> tracks,
            })
          >);

  @override
  List<_i4.Artist> getArtists() =>
      (super.noSuchMethod(
            Invocation.method(#getArtists, []),
            returnValue: <_i4.Artist>[],
          )
          as List<_i4.Artist>);

  @override
  List<_i4.Album> getAlbums() =>
      (super.noSuchMethod(
            Invocation.method(#getAlbums, []),
            returnValue: <_i4.Album>[],
          )
          as List<_i4.Album>);

  @override
  List<_i4.Track> getTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getTracks, []),
            returnValue: <_i4.Track>[],
          )
          as List<_i4.Track>);

  @override
  List<_i4.Album> getAlbumsForArtist(String? artistId) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbumsForArtist, [artistId]),
            returnValue: <_i4.Album>[],
          )
          as List<_i4.Album>);

  @override
  List<_i4.Track> getTracksForAlbum(String? albumId) =>
      (super.noSuchMethod(
            Invocation.method(#getTracksForAlbum, [albumId]),
            returnValue: <_i4.Track>[],
          )
          as List<_i4.Track>);
}

/// A class which mocks [AudioService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioService extends _i1.Mock implements _i5.AudioService {
  MockAudioService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasNext =>
      (super.noSuchMethod(Invocation.getter(#hasNext), returnValue: false)
          as bool);

  @override
  bool get hasPrevious =>
      (super.noSuchMethod(Invocation.getter(#hasPrevious), returnValue: false)
          as bool);

  @override
  bool get isPlaying =>
      (super.noSuchMethod(Invocation.getter(#isPlaying), returnValue: false)
          as bool);

  @override
  _i3.Stream<_i6.PlayerState> get playerStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#playerStateStream),
            returnValue: _i3.Stream<_i6.PlayerState>.empty(),
          )
          as _i3.Stream<_i6.PlayerState>);

  @override
  _i3.Stream<Duration> get positionStream =>
      (super.noSuchMethod(
            Invocation.getter(#positionStream),
            returnValue: _i3.Stream<Duration>.empty(),
          )
          as _i3.Stream<Duration>);

  @override
  _i3.Stream<Duration?> get durationStream =>
      (super.noSuchMethod(
            Invocation.getter(#durationStream),
            returnValue: _i3.Stream<Duration?>.empty(),
          )
          as _i3.Stream<Duration?>);

  @override
  _i3.Future<void> playShuffled(List<_i4.Track>? tracks) =>
      (super.noSuchMethod(
            Invocation.method(#playShuffled, [tracks]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> playFromAlbum(
    List<_i4.Track>? tracks, {
    int? startIndex = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #playFromAlbum,
              [tracks],
              {#startIndex: startIndex},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setQueue(_i4.PlaybackQueue? queue) =>
      (super.noSuchMethod(
            Invocation.method(#setQueue, [queue]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> skipNext() =>
      (super.noSuchMethod(
            Invocation.method(#skipNext, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> skipPrevious() =>
      (super.noSuchMethod(
            Invocation.method(#skipPrevious, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> seek(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#seek, [position]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
